table.insert(cards, {tag="Ash",	class="negative", rarity=0, ctype=CTYPE_STATUS,  range='self', energy=0, playable="unplayable"});

table.insert(cards, {tag="Dancing Flames",	class="fire",	ctype=CTYPE_ATTACK,	rarity=1, energy=0,	range="enemy",	eventAll="burned",	burn=1,	dmg=2, onUpgrade={dmg=4}});--deal 2 (4) dmg, apply 1 burn
table.insert(cards, {tag="Cremation", 		class="fire",	ctype=CTYPE_ATTACK,	rarity=1, energy=1,	range="enemy",	eventAll="burned",	dmg=9, addCards={draw={"Ash"}}, onUpgrade={dmg=12}});--deal 11 dmg, if target dies add 1 (2) Ash to your hand
table.insert(cards, {tag="Firekick", 		class="fire",	ctype=CTYPE_ATTACK,	rarity=1, energy=1,	range="enemy",	eventAll="burned",	dmg=5, burn=1, onUpgrade={dmg=7, burn=2}});--deal 5 dmg, add 1 (2) Burn
table.insert(cards, {tag="Capture Soul", 	class="fire",	ctype=CTYPE_ATTACK,	rarity=3, energy=1,	range="enemy",	dmg=15, exhaust=true, unlimited=true, dmgPerUpgrade=5, ifEnemy={condition="boss", play={upgrade=1}}, onUpgrade={}});--Deal 15 dmg. If boss (or elite) were killed, transform this card permanently into Soulshard. Exhaust overwise.
table.insert(cards, {tag="Fire Tsunami", 	class="fire",	ctype=CTYPE_ATTACK,	rarity=3, energy=3,	range="enemies",dmg=8, onUse={action="copy", target="this", to="draw"}, eventAll="burned",	exhaust=true, onUpgrade={dmg=12}});--Deal 8 (12) dmg to all enemies. Exhaust all other copies of this card from your hand. Repeat effect for each exhausted card. When you draw this card, add its copy to your hand. Exhaust.
table.insert(cards, {tag="Firelance",		class="fire",	ctype=CTYPE_ATTACK,	rarity=2, energy=1,	range="enemy",	dmg=6, eventAll="burned",	onUpgrade={dmg=10}});--Deal 6 (10) dmg, if enemy has Burn add its charges to dmg of the card until the end of the combat
table.insert(cards, {tag="Phoenix Wing", 	class="fire",	ctype=CTYPE_ATTACK,	rarity=2, energy=1,	range="enemy",	dmg=6, heal=2, eventAll="burned",	exhaust=true, onUpgrade={dmg=9, heal=3}});--deal 1 deal dmg for each card in your hand, heal your hero for the amount of dmg dealt. Exhaust.
table.insert(cards, {tag="Heatup", 			class="fire",	ctype=CTYPE_ATTACK,	rarity=2, energy=2,	range="enemy",	dmg=5, burn=2, eventAll="burned",	onUpgrade={dmg=8}});--deal 5 (8) dmg and add 2 Burn to all enemies
table.insert(cards, {tag="Arcane Explosion",class="fire",	ctype=CTYPE_ATTACK,	rarity=1, energy=1,	range="enemy",	dmg=4, once={range="enemies", dmg=2}, onUpgrade={dmg=5, once={range="enemies", dmg=4}}});--Deal 6 (9) dmg to the target and 2 (4) dmg to all other enemies

table.insert(cards, {tag="Asharmor", 		class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	range="self",	hand={action="exhaust", ctype=CTYPE_STATUS, value=true, onCount={armor=5}}, eventAll="burned",	exhaust=true, onUpgrade={hand={action="exhaust", ctype=CTYPE_STATUS, value=true, onCount={armor=8}}}});--Exhaust All Ashes from your hand, add 5 (8) Armor for each card exhausted
table.insert(cards, {tag="Burning Plates", 	class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	range="self",	burningplates=3, eventAll="burned",	exhaust=true, onUpgrade={burningplates=5}});--Add 3 (5) Burning plates. Exhaust
table.insert(cards, {tag="Flaming", 		class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	range="enemy",	flaming=1, eventAll="burned",	onUpgrade={energy=0}});--This turn whenever you deal dmg to enemy add 1 Burn
table.insert(cards, {tag="Forecast", 		class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	range="self",	draw=1, onUpgrade={draw=2}});--Whenever you draw card this turn, it costs 1 energy less. Draw 1 (2) card [?????? ???????????]
table.insert(cards, {tag="Imp Skin", 		class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	range="self",	armor=5, impskin=1, eventAll="burned",	onUpgrade={armor=8}});--(Gain 5 Armor.) This turn when you play skill add +1 Burning Plate
table.insert(cards, {tag="Magica Hunt", 	class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	range="self",	armor=5, draw=1, onUpgrade={armor=8}});--Gain 5 (8) Armor. Draw a card, if you have another copy of it in your deck draw it as well
table.insert(cards, {tag="Plague", 			class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	range="enemy",	vulnerable=2, onUpgrade={range="enemies"}});--Apply 2 Vulnerability. add buff: If target dies Vulnerable apply Plague to a random enemy (all enemies)
-- table.insert(cards, {tag="Resplash", 		class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=0,	onUpgrade={}});--Draw 1 (2) card for each card you played this turn
table.insert(cards, {tag="Power Convertion",class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=1,	hand={action="exhaust", tag='Strike', value=true, onCount={range="self", str=2}}, exhaust=true, onUpgrade={energy=0}});--Exhaust Strike from your hand, add +1 (+2) Strenght
-- table.insert(cards, {tag="Spread da BURN", 	class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=2,	eventAll="burned",	onUpgrade={}});--Choose an enemy with Burn, apply 50% (100%) amount of charges to all other enemies.
table.insert(cards, {tag="Purge", 			class="fire",	ctype=CTYPE_SKILL,	rarity=2, energy=3,	range="self",	cleanse=true, armor=15, exhaust=true, onUse={action="transform", target="all", amount="rnd", val="Ash"}, onUpgrade={armor=20}});--Remove ALL debuffs. Transform random Curse in your deck into Ash (till the end of combat). Add 10 (20) armor . Exhaust

table.insert(cards, {tag="Phoenix Form", 	class="fire",	ctype=CTYPE_POWER,	rarity=3, energy=3,	range="self", eventAll="burned",	revive=10, phoenix=2, onUpgrade={revive=15}});--Add buff: When you take leathal dmg -> set health to 10 (15), -5 max HP, add 2 "Pheonix Wing" ("Pheonix Wing+") card to your hand
table.insert(cards, {tag="Soulshard", 		class="fire",	ctype=CTYPE_POWER,	rarity=3, energy=3,	range="self", energetic=1, onUpgrade={energy=2}});-- +1 max energy until the end of combat
-- table.insert(cards, {tag="Recycling", 		class="fire",	ctype=CTYPE_POWER,	rarity=2, energy=1,	exhaust=true, onUpgrade={}});--Whenever you Exhaust 4 (3) Ashes choose a card from your hand and add its copy.
table.insert(cards, {tag="Ashmaker", 		class="fire",	ctype=CTYPE_POWER,	rarity=2, energy=1,	range="self", ashmaker=1, onUpgrade={innate=true}});--At the start of your turn: Pick up to 1 (2) card and transform it to Ash (put it into discard pile).
table.insert(cards, {tag="Simulation", 		class="fire",	ctype=CTYPE_POWER,	rarity=3, energy=2,	range="self", simulation=1, onUpgrade={innate=true}});--(Innhate.) At the start of your turn, if you have duplicates in your hand gain 1 Str

table.insert(cards, {tag="Mana Shield", 	class="fire",	ctype=CTYPE_POWER,	rarity=1, energy=1,	range="self", manashield=1, super=true, onUpgrade={energy=0}});--At the end of your turn give Armor == max energy
-- table.insert(cards, {tag="Fire Orb", 		class="fire",	ctype=CTYPE_POWER,	rarity=1, energy=1,	super=true,	eventAll="burned",	onUpgrade={}});--All "Strikes" now - Fire Cards. +2 (+3) strenght
table.insert(cards, {tag="Melting Steel",	class="fire",	ctype=CTYPE_POWER,	rarity=2, energy=1,	range="self", armorpiercing=25, super=true,	eventAll="burned",	onUpgrade={armorpiercing=50}});--Armored enemies takes 25% (50%) more dmg
-- table.insert(cards, {tag="Cripple",			class="fire",	ctype=CTYPE_POWER,	rarity=2, energy=2,	super=true,	onUpgrade={}});--When you play an Attack card, 25% (33%) chance to Weak the enemy.
-- table.insert(cards, {tag="Hardening",		class="fire",	ctype=CTYPE_POWER,	rarity=2, energy=2,	range="self", super=true,	onUpgrade={}});--When you play an Attack card other copies of this card in your hand gains +1(+2) dmg until the end of the combat.